### ISSUE TITLE
Deleted folders are still shown after deletion

### ISSUE THREAD

**Issue by derodevil** [deepak-rathi/VS2017OfflineSetupUtility#2]
This tool is impressive and very useful for me. I deleted unused old file using this tool after downloading update to version 15.8.0 manually using command prompt. After deleting I tried to re-scan the folder and all previous deleted folder were listed while those folders were successfully deleted. I checked the folder manually and yes, those old folders had disappeared but still listed as they exist.
What about the Archive folder, why don't you delete the previous version?

**Comment by deepak-rathi** [comment]
Thank @derodevil for bring this to my notice. I was not sure if users wanted "Archive" folder to be deleted. 
It take less space when compared to other old folders and files. 

1. I will add this feature to delete "Archive" folder in my next code commit. 

2. There is another issue with old folder list UI, that is even after folders are deleted some times old data is displayed in UI but there are no such folders(OLD) on hard disk. I will also fix this and commit it together with point '1'.

**Comment by derodevil** [comment]
Ok thank you for keeping this repository maintained. One more thing you may notice that there are two main buttons 

> VS2017 Offline Clean Util

 and 

> VS2017 Offline Download.

When one of them is hovered the background color turns to pale blue and that's should be. When it's clicked the color turns back to white where it's confusing because users don't realize which button is selected. I suggest to keep the background color to blue after being clicked.

**Comment by deepak-rathi** [comment]
@derodevil I had fixed the reported issue. 

> I will add this feature to delete "Archive" folder in my next code commit.

and 

> There is another issue with old folder list UI, that is even after folders are deleted some times old data is displayed in UI but there are no such folders(OLD) on hard disk. I will also fix this and commit it together with point '1'.

And also release version 1.2.0. I will close this issue.

Regarding bellow feedback:
>When one of them is hovered the background color turns to pale blue and that's should be. When it's clicked the color turns back to white where it's confusing because users don't realize which button is selected. I suggest to keep the background color to blue after being clicked.

Can you please create another issue, such that when i get some free time, I will work on it and close it when its done.
