### ISSUE TITLE
Add MSBuild

### ISSUE THREAD

**Issue by kassane** [deepak-rathi/VS2017OfflineSetupUtility#3]
Hello, you could include the msbuild only option (BuildTools).

**Comment by deepak-rathi** [comment]
I had added **build.bat** script file which can be used for building project using **MSBuild**.

You can update the MSBuild exe path to whichever version you have installed on your PC/Laptop/Device.
I was using MSBuild tool for Visual Studio 2017 and its absolute path is being used in [build.bat](https://github.com/deepak-rathi/VS2017OfflineSetupUtility/blob/master/build.bat) file.
