### ISSUE TITLE
Features type option not showing

### ISSUE THREAD

**Issue by chungweileong94** [deepak-rathi/VS2017OfflineSetupUtility#4]
For some reason nothing is showing in the features type option, both 1.1.0 & 1.2.0 version. Any idea how to debug this?

![image](https://user-images.githubusercontent.com/15154097/44782436-d1165000-abb9-11e8-95fc-b84a0ea5dec2.png)

**Comment by deepak-rathi** [comment]
Uninstall the old version. Install the new setup file i uploaded today 1.2.0. Which has this issue fixed.
You can also download the source code and run the application from "release" folder.
