### ISSUE TITLE
Wrong path

### ISSUE THREAD

**Issue by alex6dj** [deepak-rathi/VS2017OfflineSetupUtility#5]
You must enclose the path of the folder where the installation will be downloaded in quotation marks so that there is no error if the path contains blank spaces, you should also verify that there are no characters that are not allowed in it to avoid other errors.

This is the path where my download is located (there is an intermediate space between VS and Download)...

--layout D:\VS Download\Installer

![captura de pantalla 28](https://user-images.githubusercontent.com/27690651/44792567-b03b0400-ab93-11e8-99b2-d3108ada35af.png)

**Comment by deepak-rathi** [comment]
Sorry, I was busy in some other work. So could not reply back to you.

**Issue fixed in last commit.** 
I had not updated setup but if you do not wish to compile the code, you can run the executable from release folder.

Thanks for reporting this issue.
