### ISSUE TITLE
Add proxy support

### ISSUE THREAD

**Issue by Mazwak** [deepak-rathi/VS2017OfflineSetupUtility#6]
hi

I cannot use the tool to create the cache. I'm behind a proxy, and cannot access the web directly.

I'm getting a "System.Web.Netexception" error.

**Comment by Mazwak** [comment]
Maybe add a factory to create your webclients, or change every call from 

markdownText = new WebClient().DownloadString(selectedVsEdition.WorkloadGitHubUri);

to

WebClient wc = new WebClient()
IWebProxy wp = WebRequest.DefaultWebProxy;
wp.Credentials = CredentialCache.DefaultCredentials; 
wc.Proxy = wp;
markdownText = wc.DownloadString(selectedVsEdition.WorkloadGitHubUri);

As there's only two calls to webclient, a  factory might be overkill.

For reference :
https://github.com/deepak-rathi/VS2017OfflineSetupUtility/search?q=WebClient&unscoped_q=WebClient

**Comment by deepak-rathi** [comment]
Fixed in recent commit. Thanks for the details.
