### ISSUE TITLE
Offline Clean Util Problem

### ISSUE THREAD

**Issue by yasinvs** [deepak-rathi/VS2017OfflineSetupUtility#7]
Greetings, There is a problem in the section of the application I wrote in the title. If you try to scan the folder "c: \ Test" and then delete the folder after you open the application, the previous "c: \ Test" folder is not crawling without asking you and the application crashes.

Translated by Google :)

**Comment by yasinvs** [comment]
He scans the "LastSelectedFolder" setting for scanning and resumes scanning without prompting you.

**Comment by deepak-rathi** [comment]
@yasinvs  Thanks for reporting the issue. This issue is fixed in latest commit. Setup file will be updated in next 48hr but you can test the executable from "Release" folder.
