### ISSUE TITLE
What about VS2019

### ISSUE THREAD

**Issue by JPRO89-Cu** [deepak-rathi/VS2017OfflineSetupUtility#8]
What about VS2019 is it compatible

**Comment by deepak-rathi** [comment]
@JPRO89-Cu   Thanks for asking about VS2019, this motivate me to keep repo up-to-date. support for Visual Studio 2019 is added in latest commit.

You can now download VS2019 offline setup using this utility. There is no change in VS2017 clean utility as the same logic should work for both VS2017/VS2019. Let me know if you face any issue.

 Setup file will be updated in next 48hr but you can test the executable from "Release" folder.

Thanks
